# Generated by Django 5.2.7 on 2026-06-21 18:53

import apps.categories.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='CategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(max_length=500, upload_to=apps.categories.models.category_image_path, verbose_name='Ссылка на изображение')),
                ('alt', models.CharField(max_length=200, verbose_name='Альтернативный текст')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='categories.category', verbose_name='Категория товаров')),
            ],
            options={
                'verbose_name': 'Изображение категории товара',
                'verbose_name_plural': 'Изображения категорий товаров',
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Подкатегория')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='categories.category', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
            },
        ),
        migrations.CreateModel(
            name='SubcategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.ImageField(upload_to=apps.categories.models.subcategory_image_path, verbose_name='Ссылка на изображение')),
                ('alt', models.CharField(max_length=200, verbose_name='Альтернативный текст')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='categories.subcategory', verbose_name='Подкатегория товаров')),
            ],
            options={
                'verbose_name': 'Изображение подкатегории товаров',
                'verbose_name_plural': 'Изображения подкатегорий товаров',
            },
        ),
    ]
