# Generated by Django 5.2.7 on 2026-06-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_alter_basketitem_basket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketitem',
            old_name='quantity',
            new_name='count',
        ),
        migrations.AlterField(
            model_name='basketitem',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
