# Generated by Django 5.2.7 on 2026-06-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reviews',
            field=models.ManyToManyField(blank=True, null=True, related_name='product_reviews', to='reviews.review', verbose_name='Отзывы'),
        ),
    ]
