# Generated by Django 5.2.7 on 2026-06-21 21:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_alter_product_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Исходная цена товара')),
                ('sale_price', models.DecimalField(db_index=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена со скидкой')),
                ('date_from', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('date_to', models.DateTimeField(blank=True, db_index=True, default=None, verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(blank=True, db_index=True, default=True, verbose_name='Активна')),
                ('discount_type', models.CharField(choices=[('percent', 'Процентная'), ('fixed', 'Фиксированная')], max_length=10, verbose_name='Тип скидки')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
                'ordering': ['date_to'],
            },
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='catalog.product', verbose_name='Продукт')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='sales.sale', verbose_name='Скидка')),
            ],
            options={
                'verbose_name': 'Скидка на продукт',
                'verbose_name_plural': 'Скидки на продукты',
                'ordering': ['id'],
                'unique_together': {('product', 'sale')},
            },
        ),
    ]
